# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 40048e0f54b09eb68aedd8832b6c8826060b16654dacc60c70506a48f27fc1a597f4b667c7e54af44101b45cd63b4b0013868c87df00e20779a45c2d44a02f62

test:
  secret_key_base: bda35298bfdc0bb2fe95324e58e274b3cf670bd555d017192cb6ea406cdf1a12cf53de0bafd68d1ca0140f5617fe41c86d7bddaf5a970b2aa30633c9f426657b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
